"""Add GamePicks

Revision ID: 18937c2229b4
Revises: 2651f1be12e3
Create Date: 2023-07-30 13:20:53.102724

"""
import sqlalchemy as sa

# from enum import IntEnum
from alembic import op

from src.PickEmLeague.models.enums import GameResult, IntEnum

# revision identifiers, used by Alembic.
revision = "18937c2229b4"
down_revision = "2651f1be12e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_picks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("game_id", sa.Integer(), nullable=True),
        sa.Column("pick", IntEnum(GameResult), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_picks")
    # ### end Alembic commands ###
