"""Add season stats

Revision ID: 1a937b81cf57
Revises: 299a88816501
Create Date: 2023-09-10 14:01:55.603989

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import orm

from src.PickEmLeague.models.season_stats import SeasonStats
from src.PickEmLeague.models.user import User

# revision identifiers, used by Alembic.
revision = "1a937b81cf57"
down_revision = "299a88816501"
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "season_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("correct_picks", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    stats = []
    for user in session.query(User):
        stats.append(SeasonStats(user=user))
    session.add_all(stats)
    session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("season_stats")
    # ### end Alembic commands ###
