"""Add Games

Revision ID: 2651f1be12e3
Revises: a8d66e602ad6
Create Date: 2023-07-18 19:58:38.029350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2651f1be12e3'
down_revision = 'a8d66e602ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_time', sa.DateTime(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('result', sa.Enum('NOT_PLAYED', 'HOME_WIN', 'AWAY_WIN', 'TIE', name='gameresult'), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
