"""cascade delete game picks

Revision ID: 299a88816501
Revises: bb546b8f7eca
Create Date: 2023-09-07 13:01:08.221560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299a88816501'
down_revision = 'bb546b8f7eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_picks', schema=None) as batch_op:
        batch_op.drop_constraint('game_picks_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_picks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('game_picks_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
