"""add release notes

Revision ID: 3f30d324d67d
Revises: 1a937b81cf57
Create Date: 2023-09-19 15:10:47.071496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f30d324d67d'
down_revision = '1a937b81cf57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('release_notes_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry', sa.String(), nullable=False),
    sa.Column('release_notes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['release_notes_id'], ['release_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release_notes_entry')
    op.drop_table('release_notes')
    # ### end Alembic commands ###
