"""Create reads

Revision ID: 49b4cc7895ba
Revises: 3f30d324d67d
Create Date: 2023-09-20 21:01:20.431436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b4cc7895ba'
down_revision = '3f30d324d67d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('readable', sa.Integer(), nullable=True),
    sa.Column('readable_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reads_readable'), ['readable'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reads_readable'))

    op.drop_table('reads')
    # ### end Alembic commands ###
