"""Add notification toggles

Revision ID: 78499feb0749
Revises: f1abf4932269
Create Date: 2023-10-23 16:56:12.224368

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "78499feb0749"
down_revision = "f1abf4932269"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "pick_notification_enabled",
                sa.Boolean(),
                server_default=sa.sql.expression.true(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "message_notification_enabled",
                sa.Boolean(),
                server_default=sa.sql.expression.true(),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_column("message_notification_enabled")
        batch_op.drop_column("pick_notification_enabled")

    # ### end Alembic commands ###
