"""add names to user

Revision ID: bb546b8f7eca
Revises: 18937c2229b4
Create Date: 2023-08-21 22:41:04.463957

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bb546b8f7eca"
down_revision = "18937c2229b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "first_name", sa.String(length=255), nullable=False, server_default=""
            )
        )
        batch_op.add_column(
            sa.Column(
                "last_name", sa.String(length=255), nullable=False, server_default=""
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("last_name")
        batch_op.drop_column("first_name")

    # ### end Alembic commands ###
