name: TEST

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python version
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Create and start virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time

    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'
        
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
        aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
        region: us-east-1
        application_name: PickEmLeague2023
        environment_name: PickEmLeague2023-env
        version_label: "pickemleague2023-${{ steps.format-time.outputs.replaced }}" #Using timestamp create on earlier step
        deployment_package: deploy.zip
